[#19] layout 적용
let-eat-go/frontend pull request #20
Opened 2024-01-26 08:00 UTC by jexnjeux

# 구현 내용

- main 너비 지정
- header 높이 지정

# PR 유형

- [x] CSS 등 사용자 UI 디자인 변경

# 리뷰어가 집중할 내용

화면 너비 체크해 주세요!

# 관련 이슈

resolves #19

2024-01-26 09:47 UTC, River-ans approved these changes

2024-01-28 17:56 UTC, River-ans requested changes
이것도 #22  에 리뷰한 것처럼 해야 됩니다!
header 은 메인 페이지를 담은 group layout.tsx 에 담아야 됩니다.

2024-01-29 10:01 UTC, jexnjeux commented
RootLayout에서 헤더 제거했습니다!

2024-01-29 10:04 UTC, River-ans approved these changes
수고 많았습니다!

2024-01-29 10:18 UTC, merged