[#21] Routes 정의
let-eat-go/frontend pull request #22
Opened 2024-01-26 09:08 UTC by jexnjeux

# 구현 내용

Routes 정의

# PR 유형

- [x] 새로운 기능 추가

# 리뷰어가 집중할 내용

# 관련 이슈

resolves #21

2024-01-26 09:45 UTC, River-ans approved these changes
수고 하셨습니다

2024-01-28 17:52 UTC, River-ans requested changes
프로젝트의 라우팅 구조를 개선하기 위해 route groups 기능을 활용하는 것이 좋을꺼 같아요. 라우트들을 그룹화하고, 각 그룹에 공통된 레이아웃을 적용할 수 있습니다~!

1. App Layout 설정: app/layout.tsx 파일에서는 전역 레이아웃을 정의합니다. 이 파일의 body에는 {children}만 포함합니다.

2. app 디렉토리에  그룹 디랙토리를 만듭니다.!  괄호 안의 폴더는 URL에서 생략됩니다! (디렉토리 네임 예: (auth) 또는 (admin),(main) 이런식으로

3. 각 라우트 그룹별 레이아웃 설정: route groups 디렉토리 내의 각 라우트 그룹 폴더에 layout.tsx 파일을 생성하여, 해당 그룹의 공통 레이아웃을 설정할수 있습니다. 이렇게 하면 각 그룹별로 레이아웃을 적용할 수 있습니다.

[route groups ](https://nextjs.org/docs/app/building-your-application/routing/route-groups) 참고

2024-01-29 09:52 UTC, jexnjeux commented
```
app/
├── auth/
│   ├── signin/
│   ├── signup/
│   └── kakao/
└── user-activity/
    ├── meeting/
    └── mypage/
```

위 구조로 수정했습니다.

2024-01-29 10:03 UTC, River-ans approved these changes
수고하셨습니다!

2024-01-29 10:17 UTC, merged